################################################################
# Global configuration
################################################################
#
# Enable debug mode
#
# Optional, Default: false
#
# debug = false

################################################################
# Log configurations
################################################################
#
# Log level
#
# Optional, Default: "ERROR"
#
# logLevel = "INFO"

# Log file
#
# Specify path to log file.
#
# Optional Default: os.Stdout
#
# logFile = "themis.log"

################################################################
# REST API configurations
################################################################
#
# Bind Host
#
# Specify listen address.
#
# Optional, Default: localhost
#
# bindHost = "localhost"

# Bind Port
#
# Specify listen port.
#
# Optional, Default: 7878
#
# bindPort = 7878

################################################################
# Database configuration
################################################################
[database]

# Database Driver
#
# Specify Database driver and URLs so that we can persitent
# the status of all kinds of resources.
#
# All supported drivers include: mysql, postgres, sqlite3, mssql.
#
# Required, Default: sqlite3
#
# driver = "mysql"

# database connect address
#
# Required for mysql, Default: ""
#
# host = "localhost"

# database connect port
#
# Required for mysql, Default: 0
#
# port = "3306"

# database username
#
# Required for mysql, Default: themis
#
# username = "themis"

# database password
#
# Required for mysql, Default: themispass
#
# username = "themispass"

# database path
#
# Required for sqlite3, Default: themis.db
#
# path = "themis.db"

################################################################
# Monitoring configurations
################################################################
#
# We can  collect events from multiple source. each source has following format:
#
# [monitors.xxx] xxx represent is the tag for monitor; tag should be UNIQUE.
# type = xxx     xxx represent means source type, now just one type 'serf' is available.
# address = xxx  xxx specify host:port from where we can get events.
#
# from openstack environment
# [monitors.manage]
# type = "serf"
# address = "192.168.1.3:7373"
#
# [monitors.storage]
# type = "serf"
# address = "192.168.2.3:7373"
#
# [monitors.network]
# type = "serf"
# address = "192.168.3.3:7373"

################################################################
# Fence configurations
################################################################
[fence]

# Global control should we perform fence operations when we see a host became down.
#
# Optional, Default: false, which means we will take action if we see a host became down.
#
# disableFenceOps = false

################################################################
# Openstack configurations
################################################################
[openstack]
#
# provide Openstack authentication information so that we can evacuate virtual machine
# after fence operation.

# Authentication URL.
#
# Required, Default: http://localhost:5000
#
# authURL = "http://localhost:5000"

# Username
#
# Required, Default: admin
#
# username = "admin"

# User's Password
#
# Required, Default: secretxx
#
# password = "secretxx"

# Project name to scope to.
#
# Required, Default: default
#
# projectName = "admin"

# Domain name to scope to.
#
# Required, Default: default
#
# domainName = "default"

# Region name.
#
# Required, Default: RegionOne
#
# regionName = "RegionOne"

################################################################
# CatKeeper configurations
################################################################
[catkeeper]
#
# Catkeeper's url
#
# url = "http://127.0.0.1"
#
# Catkeeper's user
#
# username = "admin"